### ISSUE TITLE
Weird template render error with node 0.10.40

### ISSUE THREAD

**Issue by tuexss** [apiaryio/swagger2blueprint#15]
$ swagger2blueprint some.yml 
 Template render error: (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-apib-serializer/template.nunjucks) [Line 51, Column 23]
   Error: Unable to call `item["key"]["toValue"]`, which is undefined or falsey

Any idea what this is or how to fix it?

**Comment by kylef** [comment]
Hi @tuexss, sorry for the delay in getting back to you.

Could you test this again with the latest version of swagger2blueprint (1.0.2)?

If it's still failing, can you please share your swagger document so we can reproduce the problem?

Regards,

-Kyle

**Comment by tuexss** [comment]
Ok, I retried. This is only happening on some very large swagger file with 3k lines. When I tried a .yml with a single endpoint it ran just fine. It would be helpful if the error could indicate which line of the .yml was being processed when the exception occurred.

**Comment by kylef** [comment]
This tool has been deprecated in favour of Fury CLI. (https://github.com/apiaryio/swagger2blueprint/pull/27). I could imagine that this is likely fixed in Fury CLI already. I am not able to re-test as you never did share a Swagger document that could reproduce the problem.

If this problem is still valid in Fury CLI please let us know.
